services:
  database:
    image: "postgres:16.10-alpine3.22"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"

  web:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: local_user
      POSTGRES_DB: local_db
      POSTGRES_PASSWORD: local_password
    depends_on:
      - database
