services:
  database:
    image: "postgres:16.10-alpine3.22"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db
    ports:
      - "5432:5432"
